# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('tsn', ['core','traffic-control'])
    module.source = [
      	'model/transmisson-gate-qdisc.cc',
      	'model/net-device-list-config.cc',
        'model/TsnIpv4PacketFilter.cc',
        'model/TsnIpv6PacketFilter.cc',
        'model/tas-queue-disc.cc',
        'helper/tsn-helper.cc',
        'test/Ipv4Filter.cc',
        'test/tas-test.cc',
        ]

    module_test = bld.create_ns3_module_test_library('tsn')
    module_test.source = [
        'test/tsn-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/tsn-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'tsn'
    headers.source = [
    	'model/transmisson-gate-qdisc.h',
    	'model/net-device-list-config.h',
        'model/TsnIpv4PacketFilter.h',
        'model/TsnIpv6PacketFilter.h',
        'model/tas-queue-disc.h',
        'helper/tsn-helper.h',
        'test/Ipv4Filter.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

